trigger: none

resources:
  pipelines:
    - pipeline: ci-pipeline
      source: 'test-icinema-ci-pipeline'
      trigger:
        branches: ['main']

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'VG-TEST-ICINEMA'
  azureSubscription: 'SC-ARM-TEST-ICINEMA'
  webAppName: 'SERVIDOR-API-TEST'
  resourceGroup: 'test-icinema-academic'
  # AGREGAR ESTA VARIABLE CRÍTICA:
  imageRepository: 'daldeoscoder/icinema-api'

stages:
  - stage: Deploy
    displayName: Deploy to Azure
    jobs:
      - deployment: Deploy
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appName: $(webAppName)
                    # CORREGIR: Usar el tag del pipeline CI
                    containers: '$(imageRepository):latest'
                    appSettings: |
                      -name DATABASE_URL -value "$(DATABASE_URL)"
                      -name WEBSITES_PORT -value "8000"